# .gitlab-ci.yml for pubswh-ui
#
# == Reference:
#   - https://sas.cr.usgs.gov/
#   - https://docs.gitlab.com/ee/ci/yaml/
#   - https://docs.gitlab.com/ee/ci/multi_project_pipelines.html
#
# == CI Variables:
#   The following CI variables are expected to be set outside of this file.
#
#   ARTIFACTORY_BASE_URL
#     The base URL for the SAS group's Artifactory for uploading the
#     asset artifact.
#
#   ARTIFACTORY_TOKEN
#     A token used to authenticate with SAS Artifactory for uploading the
#     asset artifact.
#
#   CI_REGISTRY
#     Address to the Docker image registry.
#     This is a built-in Docker variable that, by default, points to the internal
#     Docker Image registry.
#
#   CI_REGISTRY_USER
#     The username for authenticating with the Docker image registry.
#     Defaults to "gitlab-ci-token"
#
#   CI_REGISTRY_PASS
#     The password. for authenticating with the Docker image registry.
#     Defaults to "$CI_JOB_TOKEN"
#     This is restricted to protected branches and tags!
#
#   DEPLOY_TRIGGER_TOKEN
#     The API token for the deployment pipeline as configured on the deployment
#     repository.
#
#   DEPLOY_TRIGGER_URL
#     The API URL for the deployment pipeline as configured on the deployment
#     repository.
#
stages:
  - Build
  - Package Assets
  - Trigger Deployment

variables:
  # The full name of the Docker image to produce, including the registry address.
  # In most cases, this should be left alone.
  IMAGE_NAME: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
  IMAGE_TAG: ${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  # The asset files are packaged and uploaded to Artifactory for deployment.
  # This sets the filename to use for the artifact.
  ASSET_ARTIFACT_FILE: pubswh-assets-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}.zip

#
# == Docker Build
#
Build Docker Image:
  image: code.chs.usgs.gov:5001/sas/ops/docker/base-images/docker:19-latest
  stage: Build
  services:
    - docker:dind
  tags:
    - docker
  only:
    variables:
      # We must run on a protected branch to access the CI_REGISTRY_PASS variable.
      - $CI_COMMIT_REF_PROTECTED == "true"
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASS} ${CI_REGISTRY}
  script:
    - docker build
      --pull
      -t ${IMAGE_NAME}:${IMAGE_TAG}
      --build-arg python_image=${SAS_IMAGES_URL}/python
      --build-arg python_image_tag=3.7-slim-buster
      -f Dockerfile-ci .
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}

#
# == Build Static Assets
#
Build Assets:
  image: ${SAS_IMAGES_URL}/node:12.16
  stage: Build
  tags:
    - docker
  script:
    - cd assets
    - npm install
    - npx bower install --allow-root
    - npm run build
  artifacts:
    paths:
      - assets/dist

#
# == Upload Assets to Artifactory
#
# This job zips the "assets/" directory and uploads it to Artifactory. The URL
# to # the artifact is passed in the deployment trigger.
#
# NOTE: This uses an ARTIFACTORY_TOKEN, which is specified as a global ci
Package Assets:
  image: ${SAS_IMAGE_DEPLOY_TOOL}
  stage: Package Assets
  dependencies:
    - Build Assets
  tags:
    - docker
  only:
    variables:
      - $CI_COMMIT_REF_PROTECTED == "true"
  script:
    - 'zip -9 -r ${ASSET_ARTIFACT_FILE} assets/dist'
    # Compute the sha1sum of the .zip file for uploading to artifactory.
    - export SHA1SUM_ASSET_FILE=$(sha1sum ${ASSET_ARTIFACT_FILE} | cut -d " " -f1)
    - curl --fail -k
      -H "X-JFrog-Art-Api:${ARTIFACTORY_TOKEN}"
      -H "X-Checksum-Sha1:${SHA1SUM_ASSET_FILE}"
      -T ${ASSET_ARTIFACT_FILE}
      ${ARTIFACTORY_BASE_URL}/pubswh/${ASSET_ARTIFACT_FILE}

#
# == Deployment Triggers
#
# These jobs use 'curl' to make a request to the GitLab API to trigger the
# deployment repository's pipeline. The pipeline trigger is configured on
# the deployment repository under "Settings -> CI/CD -> Pipeline Triggers",
# which provides an API URL and token.
#
# References:
#   - https://docs.gitlab.com/ee/ci/triggers/README.html
#
.deploy_trigger:
  image: ${SAS_IMAGES_URL}/curl:master-latest
  stage: Trigger Deployment
  tags:
    - docker
  only:
    variables:
      - $CI_COMMIT_REF_PROTECTED == "true"
  script:
    - curl -X POST
      -F variables[PUBSWH_UI_IMAGE]=${IMAGE_NAME}
      -F variables[PUBSWH_UI_IMAGE_TAG]=${IMAGE_TAG}
      -F variables[ASSET_ARTIFACT_URL]=${ARTIFACTORY_BASE_URL}/pubswh/${ASSET_ARTIFACT_FILE}
      -F token=${DEPLOY_TRIGGER_TOKEN}
      -F ref=${DEPLOY_TRIGGER_REF}
      ${DEPLOY_TRIGGER_URL}

Development deployment:
  extends: .deploy_trigger
  only:
    refs:
      - master
  variables:
    # The branch of the deployment repository to trigger.
    DEPLOY_TRIGGER_REF: develop

Staging deployment:
  extends: .deploy_trigger
  only:
    refs:
      - master
  variables:
    # The branch of the deployment repository to trigger.
    DEPLOY_TRIGGER_REF: release
